/* eslint-disable prettier/prettier */
/* eslint-disable semi */
/* eslint-disable eol-last */
export default {
    home: require('../assets/images/icon_home.png'),
    policy: require('../assets/images/icon_policy.png'),
    history: require('../assets/images/icon_history.png'),
    account: require('../assets/images/icon_account.png'),
    bell: require('../assets/images/icon_bell.png'),
    scanner: require('../assets/images/icon_scanner.png'),
    shopping: require('../assets/images/shopping.png'),
    superApp: require('../assets/images/service_superApp.png'),
    superPay: require('../assets/images/service_superPay.png'),
    tradeFair: require('../assets/images/service_tradeFair.png'),
    workGame: require('../assets/images/service_workGame.png'),
    suppon: require('../assets/images/service_suppon.png'),
    banner: require('../assets/images/banner.png'),
    wallet: require('../assets/images/icon_wallet.png'),
    commission: require('../assets/images/icon_commission.png'),
    deposit: require('../assets/images/icon_deposit.png'),
    withdraw: require('../assets/images/icon_withdraw.png'),
    transfer: require('../assets/images/icon_transfer.png'),
    pay: require('../assets/images/icon_pay.png'),
    cashWallet: require('../assets/images/icon_cash_wallet.png'),
    commissionWallet: require('../assets/images/icon_commission_wallet.png'),
    bonusWallet: require('../assets/images/icon_bonus_wallet.png'),
    arrow: require('../assets/images/icon_arrow.png'),
    change: require('../assets/images/icon_change.png'),
    walletLevel: require('../assets/images/wallet_level.png'),
    avatar: require('../assets/images/avatar.png'),
}